// Generated by Selenium IDE

using System.Collections.Generic;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using NUnit.Framework;

namespace NUnitAutoTests
{
    [TestFixture]
    public class AdminPageDeleteUserTest
    {
        private IWebDriver _webDriver;

        [SetUp]
        public void SetUp()
        {
            var service =
                ChromeDriverService.CreateDefaultService(@"C:\Users\Vladislav Avanesov\Downloads\chromedriver_win32");
            service.HideCommandPromptWindow = true;
            _webDriver = new ChromeDriver(service);
        }

        [TearDown]
        protected void TearDown()
        {
            _webDriver.Quit();
        }

        [Test]
        public void AdminPageDeleteUser()
        {
            _webDriver.Navigate().GoToUrl("https://localhost:5001");
            _webDriver.Manage().Window.Size = new System.Drawing.Size(1916, 1040);
            _webDriver.FindElement(By.Id("email")).SendKeys("qweqweeqw@gmail.com");
            _webDriver.FindElement(By.Id("password")).SendKeys("1QWEqwe!");
            _webDriver.FindElement(By.CssSelector("#signIn > .MuiButton-label")).Click();
            Thread.Sleep(3000);

            var elementsBeforeRemoveUser = _webDriver.FindElements(By.CssSelector("#root > div > div > ul > li"));
            _webDriver.FindElement(
                    By.XPath($"/html/body/div/div/div/ul/li[{elementsBeforeRemoveUser.Count - 1}]/div[2]/button[1]"))
                .Click();
            var elementsAfterRemoveUser = _webDriver.FindElements(By.CssSelector("#root > div > div > ul > li"));

            Assert.IsTrue(elementsBeforeRemoveUser != elementsAfterRemoveUser);
        }

        [Test]
        public void AdminPageUpdateUser()
        {
            _webDriver.Navigate().GoToUrl("https://localhost:5001");
            _webDriver.Manage().Window.Size = new System.Drawing.Size(1916, 1040);
            _webDriver.FindElement(By.Id("email")).SendKeys("qweqweeqw@gmail.com");
            _webDriver.FindElement(By.Id("password")).SendKeys("1QWEqwe!");
            _webDriver.FindElement(By.CssSelector("#signIn > .MuiButton-label")).Click();
            Thread.Sleep(3000);

            var updateUserId = _webDriver.FindElements(By.CssSelector("#root > div > div > ul > li")).Count;
            _webDriver.FindElement(By.XPath($"/html/body/div/div/div/ul/li[{updateUserId - 1}]/div[2]/button[2]"))
                .Click();

            _webDriver.FindElement(By.XPath($"/html/body/div[2]/div[3]/div/form/div[2]/div[1]/div/input"))
                .SendKeys("Ярик");
            _webDriver.FindElement(By.XPath($"/html/body/div[2]/div[3]/div/form/div[2]/div[2]/div/input"))
                .SendKeys("Ткаченко");
            _webDriver.FindElement(By.XPath($"/html/body/div[2]/div[3]/div/form/div[2]/div[3]/div/input"))
                .SendKeys("qweqweeqw@gmail.com");


            _webDriver.FindElement(By.XPath($"/html/body/div[2]/div[3]/div/form/div[3]/button[1]")).Click();
            var updatedName = _webDriver
                .FindElement(By.XPath($"/html/body/div/div/div/ul/li[{updateUserId - 1}]/div[2]/div[1]")).Text;

            Assert.IsTrue(updatedName == "Ярик");
        }
    }
}