version: "3.9"
services:
    backend:
        build:
           context: .
           dockerfile: ./Dockerfile
        # image: todolistwebapp
        container_name: todolistwebapp
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        restart: on-failure
        ports:
            - 5000:80
            - 5001:443
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        depends_on:
            - db
    db:
        container_name: sqlserver
        hostname: sqlserver
        ports:
        - 1437:1433
        volumes:
        - sql-server-volume:/var/opt/mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=reallyStrongPwd#123
        - MSSQL_MEMORY_LIMIT_MB=2000
        restart: always
        healthcheck:
            test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "reallyStrongPwd#123", "-Q", "SELECT 1", "||", "exit", "1"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    sql-server-volume:
                